<?php

namespace StoreBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * DescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptionRepository extends DocumentRepository
{
    
    public function removeDescription($productDescription)
{
    return $this
        ->createQueryBuilder()
        ->update()
        ->field('productDescription')->pull($productDescription)
        ->multiple(true)
        ->getQuery()
        ->execute();
}
    
}